# Generated by Django 5.1.3 on 2024-12-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('employees', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('birthday', 'Birthday'), ('private', 'Private Party')], max_length=50, verbose_name='Event Type')),
                ('number_of_guests', models.PositiveIntegerField(verbose_name='Number of Guests')),
                ('venue_name', models.CharField(max_length=255, verbose_name='Venue Name')),
                ('venue_address', models.TextField(verbose_name='Venue Address')),
                ('venue_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Venue Contact')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Special Instructions')),
                ('decorations_required', models.BooleanField(default=False, verbose_name='Decorations Required')),
                ('logistics_notes', models.TextField(blank=True, null=True, verbose_name='Logistics Notes')),
                ('event_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Event Cost')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('event_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Event Status')),
                ('event_notes', models.TextField(blank=True, null=True, verbose_name='Event Notes')),
                ('assigned_staff', models.ManyToManyField(blank=True, related_name='assigned_events', to='employees.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='client.customer')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu', verbose_name='Menu')),
            ],
        ),
    ]
