# Generated by Django 4.2.7 on 2024-12-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_tables',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Tables'),
        ),
        migrations.AddField(
            model_name='event',
            name='price_of_decoration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price of Decoration'),
        ),
        migrations.AddField(
            model_name='event',
            name='price_of_extras',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price of Extras'),
        ),
        migrations.AddField(
            model_name='event',
            name='price_per_table',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price per Table'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Event Cost'),
        ),
    ]
