# Generated by Django 4.2.7 on 2024-12-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_dessert_alter_menu_first_main_plate_and_more'),
        ('events', '0004_alter_event_event_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='event',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='event',
            name='selected_dishes',
            field=models.ManyToManyField(related_name='events', to='menu.dish', verbose_name='Selected Dishes'),
        ),
    ]
