# Generated by Django 4.2.7 on 2024-12-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_cost_alter_event_event_status_and_more'),
        ('events', '0006_alter_event_number_of_guests'),
    ]

    operations = [
    ]
