# Generated by Django 4.2.7 on 2024-12-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_type_alter_event_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Programmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=20, verbose_name='Event Status'),
        ),
    ]
