# Generated by Django 4.2.7 on 2024-12-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_merge_20241225_1653'),
        ('events', '0008_alter_event_event_status'),
    ]

    operations = [
    ]
