# Generated by Django 4.2.7 on 2024-12-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20241226_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Programmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=20, verbose_name='Event Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', 'Mariage'), ('corporate', "Événement d'entreprise"), ('birthday', 'Anniversaire'), ('private', 'Fête privée'), ('engagement', 'Fiançailles'), ('baptism', 'Baptême'), ('marriage_signature', "Signature d'acte de mariage"), ('family_reunion', 'Réunion de famille'), ('conference', 'Conférence'), ('charity_event', 'Événement caritatif'), ('graduation', 'Remise de diplômes'), ('baby_shower', 'Fête de naissance'), ('festival', 'Festival'), ('exhibition', 'Exposition'), ('concert', 'Concert'), ('anniversary', 'Anniversaire de mariage'), ('new_year', 'Nouvel An'), ('retirement', 'Départ à la retraite')], max_length=50, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_guests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Guests'),
        ),
        migrations.CreateModel(
            name='EventProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event')),
            ],
        ),
    ]
