# Generated by Django 4.2.7 on 2024-12-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_event_status_alter_event_event_type_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='event',
            name='selected_products',
            field=models.ManyToManyField(related_name='events', through='events.EventProduct', to='products.product', verbose_name='Selected Products'),
        ),
    ]
