# Generated by Django 4.2.7 on 2025-01-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20241225_1931'),
        ('events', '0011_eventproduct_product_event_selected_products'),
    ]

    operations = [
    ]
