# Generated by Django 4.2.7 on 2025-01-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_merge_20241229_1333'),
        ('events', '0012_merge_20250112_1631'),
    ]

    operations = [
    ]
