# Generated by Django 4.2.7 on 2025-01-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_merge_20250112_1609'),
        ('events', '0013_merge_20250118_2246'),
    ]

    operations = [
    ]
