version: '3.8'

services:
  django:
    build:
      context: .
    container_name: system_traiteur_django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: system_traiteur_db
    environment:
      POSTGRES_USER: traiteur_user
      POSTGRES_PASSWORD: traiteur_password
      POSTGRES_DB: traiteur_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
