# Generated by Django 5.1.3 on 2024-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('department', models.CharField(choices=[('decoration', 'Decoration'), ('cooking', 'Cooking'), ('service', 'Service'), ('logistics', 'Logistics')], max_length=50, verbose_name='Department')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('chef', 'Chef')], max_length=50, verbose_name='Role')),
                ('start_date', models.DateField(verbose_name='Date of Start')),
                ('pay_per_event', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pay Per Event')),
            ],
        ),
    ]
