# Generated by Django 4.2.7 on 2024-12-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('chef', 'Chef'), ('photograph', 'Photograph'), ('waiter', 'Serveur')], max_length=50, verbose_name='Role'),
        ),
    ]
