# Generated by Django 5.1.3 on 2024-12-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Material Name')),
                ('category', models.CharField(choices=[('seating', 'Seating'), ('tables', 'Tables'), ('dinnerware', 'Dinnerware'), ('decorations', 'Decorations'), ('equipment', 'Equipment')], max_length=50, verbose_name='Category')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='Total Quantity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
    ]
