# Generated by Django 5.1.3 on 2024-12-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('events', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Assigned Role')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
            ],
            options={
                'unique_together': {('employee', 'event')},
            },
        ),
        migrations.CreateModel(
            name='MaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.PositiveIntegerField()),
                ('date_allocated', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='events.event')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='materials.material')),
            ],
            options={
                'unique_together': {('material', 'event')},
            },
        ),
    ]
