# Generated by Django 5.1.3 on 2024-12-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('events', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialAllocation',
            new_name='EventMaterialAllocation',
        ),
        migrations.AlterUniqueTogether(
            name='eventmaterialallocation',
            unique_together=set(),
        ),
    ]
