# Generated by Django 4.2.7 on 2024-12-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desserts', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='first_main_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_main_dishes', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='second_main_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_main_dishes', to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='starter_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_dishes', to='menu.dish'),
        ),
    ]
