# Generated by Django 4.2.7 on 2024-12-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0010_alter_event_event_status_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('type', models.CharField(choices=[('sweet', 'Sweets'), ('salted', 'Salted'), ('cake', 'Cakes'), ('soire', 'Soirée Items')], max_length=50, verbose_name='Product Type')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
            ],
        ),
        migrations.CreateModel(
            name='EventProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity Required')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_products', to='events.event')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_products', to='products.product')),
            ],
        ),
    ]
