# Generated by Django 4.2.7 on 2025-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('sweet', 'Sucres'), ('salted', 'Sales'), ('cake', 'Tartes'), ('soire', 'Petit Soiree')], max_length=50, verbose_name='Product Type'),
        ),
    ]
